### GET all notes
GET {{host}}/notes
Accept: application/json;

### POST a note
POST {{host}}/api/notes
Accept: application/json;
Content-Type: application/json

{
  "content": "Заметочка заметка замечательная 5"
}

### DELETE a note
DELETE {{host}}/api/notes?id=e3a10c17-f9ce-4177-b6d9-ae44c4c40aa2

### OPTIONS a note
OPTIONS {{host}}/api/notes
Accept: application/json;

###





